In [1]:
import numpy as np
from scipy.special import softmax
import random
import pandas as pd

# hyperparameters
no_puzzlepieces = 3
no_instances = 1000
std = 0.5 # noise in coordinate confidence
std_inst = 0.5 # noise in instruction confidence
coord = list(range(no_puzzlepieces))
scale_up_factor = 2   # parameter to scale up all values before softmaxing to prevent all values from being all too similar
scale_up_factor_inst = 2 

# storing intermediate and final data
X=[]

X_coord_conf_ideal =[]
X_coord_conf_noisy =[]

X_inst_conf_ideal =[]
X_inst_conf_noisy =[]

X_mov_vec = []

y = []

# Instructions and Instruction Confidence

In [2]:
for m in range(no_instances):
        
    print('\n')
    print(f'instance: {m}')
    
    inst_p_ideal = []
    inst_p_noisy = []
    
    for group in range(3):
        
        print('\n')
        print(f'group: {group}')
        
        #############################################################################
        ############## SET TRUE INSTRUCTION CONFIDENCE ##############################
        #############################################################################
        
        current_inst_p_ideal = random.randint(0,1)
        print(current_inst_p_ideal)
        inst_p_ideal.append(current_inst_p_ideal)
        
        
        #############################################################################
        ########################  NORMALLY DISTRIBUTED NOISE ########################
        #############################################################################
        
        # create an auxilary probability that an instruction was not given (1 - inst_p) 
        inst_p_ideal_aux = []
        
        inst_p_ideal_aux.append(current_inst_p_ideal) # probability that an instruction was given
        
        if current_inst_p_ideal == 0: # probability that an instruction was not given
            inst_p_ideal_aux.append(1) 
        else:
            inst_p_ideal_aux.append(0)   
        
        # noise up those ideal probabilities (n) for "instruction was given" and "instruction was not given"
        inst_p_noisy_aux = []
        for n in range(2):
            inst_p_noisy_aux.append(np.random.normal(scale = std_inst, loc = inst_p_ideal_aux[n], size = 1)[0])
        
        # upscale values
        inst_p_noisy_aux_upscaled = np.multiply(inst_p_noisy_aux, scale_up_factor_inst)                               

        # squash values to sum up to one to represent probabilities
        inst_p_noisy_aux_squashed = softmax(inst_p_noisy_aux_upscaled)
        
        
        print(inst_p_noisy_aux_squashed[0])
        inst_p_noisy.append(inst_p_noisy_aux_squashed[0])
    
    # store
    X_inst_conf_ideal.append(inst_p_ideal)
    X_inst_conf_noisy.append(inst_p_noisy)




instance: 0


group: 0
1
0.9871418360621238


group: 1
1
0.8736934932953251


group: 2
0
0.23965428284977058


instance: 1


group: 0
0
0.14022966076151402


group: 1
1
0.881407778462494


group: 2
1
0.9930919896365772


instance: 2


group: 0
0
0.05352595671420031


group: 1
1
0.2768953439967746


group: 2
1
0.9555471928035614


instance: 3


group: 0
0
0.007082638229653576


group: 1
1
0.7487333294567681


group: 2
1
0.9774143542456813


instance: 4


group: 0
1
0.7213315840829096


group: 1
1
0.9262674436922799


group: 2
1
0.9967836748951346


instance: 5


group: 0
0
0.01536639746277958


group: 1
0
0.17232036507564752


group: 2
0
0.03965191733665066


instance: 6


group: 0
1
0.853877257261257


group: 1
1
0.5076131364912541


group: 2
0
0.15169348053598716


instance: 7


group: 0
0
0.08608150870075806


group: 1
1
0.777933742695756


group: 2
1
0.6570126428078342


instance: 8


group: 0
1
0.9889287970731696


group: 1
0
0.2654269461603875


group: 2
1
0.9417669339127344


i

# Coordinates and Coordinate Confidence

In [3]:
for m in range(no_instances):
    
    
    print('\n')
    print(f'instance: {m}')
    

    #############################################################################
    ############## SET TRUE COORDINATE & IDEAL PROBABILITIES ####################
    #############################################################################


    # set all coordinate probabilities p = 0.0
    coordinate_p_ideal = np.zeros(no_puzzlepieces)

    # determine true coordinate and set its probability to p = 1.0
    i = random.randint(0,no_puzzlepieces-1)
    coordinate_p_ideal[i] = 1.0

    # show all probabilities
    print(coordinate_p_ideal)
    
    # store ideal probabilities
    X_coord_conf_ideal.append(coordinate_p_ideal)


    #############################################################################
    ########################  NORMALLY DISTRIBUTED NOISE ########################
    #############################################################################

    
    # auxilary lists to store different group's outputs per instance
    both_groups = []
    for group in range(2):

        # add normally distributed noise on ideal probabilities 
        coordinate_p_noisy = []
        for i in range(no_puzzlepieces):
            coordinate_p_noisy.append(np.random.normal(scale = std, loc = coordinate_p_ideal[i], size = 1)[0])

        # upscale values
        coordinate_p_noisy_upscaled = np.multiply(coordinate_p_noisy, scale_up_factor)                               

        # squash values to sum up to one to represent probabilities
        coordinate_p_noisy_squashed = softmax(coordinate_p_noisy_upscaled)

        # save group's probability distribution in overall df
        both_groups.append(coordinate_p_noisy_squashed)
        print(both_groups[group])

    #X.append(both_groups)
    X_coord_conf_noisy.append(both_groups)




instance: 0
[0. 1. 0.]
[0.51462596 0.38261718 0.10275686]
[0.02827888 0.91239123 0.05932989]


instance: 1
[1. 0. 0.]
[0.81556219 0.12933925 0.05509856]
[0.60761736 0.16095757 0.23142507]


instance: 2
[0. 1. 0.]
[0.02480283 0.84186557 0.1333316 ]
[0.01838135 0.93550498 0.04611366]


instance: 3
[0. 0. 1.]
[0.39070013 0.11504986 0.49425001]
[0.21456618 0.04607033 0.73936348]


instance: 4
[0. 1. 0.]
[0.02871562 0.79293789 0.17834649]
[0.07684708 0.86518879 0.05796412]


instance: 5
[0. 1. 0.]
[0.14661634 0.43497791 0.41840575]
[0.06047887 0.84926954 0.09025159]


instance: 6
[0. 0. 1.]
[0.65588952 0.25531683 0.08879365]
[0.16027708 0.07585073 0.76387219]


instance: 7
[0. 1. 0.]
[0.01729983 0.93724871 0.04545146]
[0.01521609 0.90302919 0.08175473]


instance: 8
[1. 0. 0.]
[0.59084015 0.15034879 0.25881106]
[0.3886399 0.2805404 0.3308197]


instance: 9
[0. 0. 1.]
[0.71583382 0.1715049  0.11266128]
[0.05683816 0.15934323 0.78381861]


instance: 10
[0. 1. 0.]
[0.14770278 0.1975645  0.65

# Moving Vector

In [4]:
#X_mov_vec = []
for m in range(no_instances):
    X_mov_vec.append(['dummy moving vector'])

# Gold Label

In [5]:
for m in range(no_instances):
    
    # language group outputs  
    if X_inst_conf_ideal[m][2]==1:
        y.append(X_mov_vec[m])
        
    # language and vision group outputs
    elif X_inst_conf_ideal[m][0]==1:
        y.append(X_coord_conf_ideal[m])
        
    # gesture group outputs
    elif X_inst_conf_ideal[m][1]==1:
        y.append(X_coord_conf_ideal[m])
        
    # noone outputs
    else:
        y.append('NaN')
    
    print(f'instance: {m}')
    print(y[m])
    print('\n')


instance: 0
[0. 1. 0.]


instance: 1
['dummy moving vector']


instance: 2
['dummy moving vector']


instance: 3
['dummy moving vector']


instance: 4
['dummy moving vector']


instance: 5
NaN


instance: 6
[0. 0. 1.]


instance: 7
['dummy moving vector']


instance: 8
['dummy moving vector']


instance: 9
['dummy moving vector']


instance: 10
[0. 1. 0.]


instance: 11
[0. 1. 0.]


instance: 12
[0. 1. 0.]


instance: 13
[0. 0. 1.]


instance: 14
['dummy moving vector']


instance: 15
NaN


instance: 16
[0. 1. 0.]


instance: 17
['dummy moving vector']


instance: 18
['dummy moving vector']


instance: 19
['dummy moving vector']


instance: 20
[0. 0. 1.]


instance: 21
['dummy moving vector']


instance: 22
[0. 1. 0.]


instance: 23
[1. 0. 0.]


instance: 24
[1. 0. 0.]


instance: 25
[0. 0. 1.]


instance: 26
['dummy moving vector']


instance: 27
[0. 0. 1.]


instance: 28
[1. 0. 0.]


instance: 29
['dummy moving vector']


instance: 30
['dummy moving vector']


instance: 31
['dummy mo

# Store All

In [6]:
X = {'Instruction':X_inst_conf_ideal,'Instruction Confidence':X_inst_conf_noisy, 'Coordinate': X_coord_conf_ideal , 'Coordinate Confidence':X_coord_conf_noisy, 'Moving Vector':X_mov_vec}
df_X = pd.DataFrame(X)
df_X


Instruction                             Instruction Confidence  \
0     [1, 1, 0]  [0.9871418360621238, 0.8736934932953251, 0.239...   
1     [0, 1, 1]  [0.14022966076151402, 0.881407778462494, 0.993...   
2     [0, 1, 1]  [0.05352595671420031, 0.2768953439967746, 0.95...   
3     [0, 1, 1]  [0.007082638229653576, 0.7487333294567681, 0.9...   
4     [1, 1, 1]  [0.7213315840829096, 0.9262674436922799, 0.996...   
..          ...                                                ...   
995   [0, 0, 0]  [0.07606120158818509, 0.15803787109136783, 0.2...   
996   [0, 1, 0]  [0.408381963472507, 0.9932957360454397, 0.0308...   
997   [1, 1, 0]  [0.9904749089325618, 0.9303057556044185, 0.033...   
998   [1, 0, 1]  [0.909421047873664, 0.013507619231403216, 0.85...   
999   [1, 0, 1]  [0.8639813007363923, 0.47042586682619686, 0.35...   

          Coordinate                              Coordinate Confidence  \
0    [0.0, 1.0, 0.0]  [[0.5146259619752814, 0.3826171820444913, 0.10...   
1    [1.0, 0.0, 0.0]  [[0.8155621910724177, 0.12933925186935516, 0.0...   
2    [0.0, 1.0, 0.0]  [[0.024802826347074244, 0.8418655691635647, 0....   
3    [0.0, 0.0, 1.0]  [[0.3907001284220422, 0.11504985722160023, 0.4...   
4    [0.0, 1.0, 0.0]  [[0.028715618992823724, 0.79293788964323, 0.17...   
..               ...                                                ...   
995  [0.0, 1.0, 0.0]  [[0.11340357131779344, 0.8100429593006556, 0.0...   
996  [0.0, 1.0, 0.0]  [[0.0640081222441194, 0.9216858401139667, 0.01...   
997  [0.0, 0.0, 1.0]  [[0.4696938193641581, 0.04278655335370268, 0.4...   
998  [0.0, 1.0, 0.0]  [[0.00483117073891031, 0.9850404454837598, 0.0...   
999  [0.0, 1.0, 0.0]  [[0.13378949599442327, 0.8485795138837519, 0.0...   

             Moving Vector  
0    [dummy moving vector]  
1    [dummy moving vector]  
2    [dummy moving vector]  
3    [dummy moving vector]  
4    [dummy moving vector]  
..                     ...  
995  [dummy moving vector]  
996  [dummy moving vector]  
997  [dummy moving vector]  
998  [dummy moving vector]  
999  [dummy moving vector]  

[1000 rows x 5 columns]

In [7]:
y = {'DM output': y}
df_y = pd.DataFrame(data=y)
df_y

DM output
0          [0.0, 1.0, 0.0]
1    [dummy moving vector]
2    [dummy moving vector]
3    [dummy moving vector]
4    [dummy moving vector]
..                     ...
995                    NaN
996        [0.0, 1.0, 0.0]
997        [0.0, 0.0, 1.0]
998  [dummy moving vector]
999  [dummy moving vector]

[1000 rows x 1 columns]

In [8]:
X_DM = df_X.to_json(r'/Users/clarawicharz/Desktop/CogSys/ROBO_neu/data/X_DM.json', orient='index')
y_DM = df_y.to_json(r'/Users/clarawicharz/Desktop/CogSys/ROBO_neu/data/y_DM.json', orient='index')