In [1]:
import numpy as np
from scipy.special import softmax
import random
import pandas as pd

# hyperparameters
no_puzzlepieces = 3
no_instances = 10
std = 0.5 # noise in coordinate confidence
std_inst = 0.5 # noise in instruction confidence
coord = list(range(no_puzzlepieces))
scale_up_factor = 2   # parameter to scale up all values before softmaxing to prevent all values from being all too similar
scale_up_factor_inst = 2 

# storing intermediate and final data
X=[]

X_coord_conf_ideal =[]
X_coord_conf_noisy =[]

X_inst_conf_ideal =[]
X_inst_conf_noisy =[]

X_mov_vec = []

y = []

# Instructions and Instruction Confidence

In [2]:
for m in range(no_instances):
        
    print('\n')
    print(f'instance: {m}')
    
    inst_p_ideal = []
    inst_p_noisy = []
    
    for group in range(3):
        
        print('\n')
        print(f'group: {group}')
        
        #############################################################################
        ############## SET TRUE INSTRUCTION CONFIDENCE ##############################
        #############################################################################
        
        current_inst_p_ideal = random.randint(0,1)
        print(current_inst_p_ideal)
        inst_p_ideal.append(current_inst_p_ideal)
        
        
        #############################################################################
        ########################  NORMALLY DISTRIBUTED NOISE ########################
        #############################################################################
        
        # create an auxilary probability that an instruction was not given (1 - inst_p) 
        inst_p_ideal_aux = []
        
        inst_p_ideal_aux.append(current_inst_p_ideal) # probability that an instruction was given
        
        if current_inst_p_ideal == 0: # probability that an instruction was not given
            inst_p_ideal_aux.append(1) 
        else:
            inst_p_ideal_aux.append(0)   
        
        # noise up those ideal probabilities (n) for "instruction was given" and "instruction was not given"
        inst_p_noisy_aux = []
        for n in range(2):
            inst_p_noisy_aux.append(np.random.normal(scale = std_inst, loc = inst_p_ideal_aux[n], size = 1)[0])
        
        # upscale values
        inst_p_noisy_aux_upscaled = np.multiply(inst_p_noisy_aux, scale_up_factor_inst)                               

        # squash values to sum up to one to represent probabilities
        inst_p_noisy_aux_squashed = softmax(inst_p_noisy_aux_upscaled)
        
        
        print(inst_p_noisy_aux_squashed[0])
        inst_p_noisy.append(inst_p_noisy_aux_squashed[0])
    
    # store
    X_inst_conf_ideal.append(inst_p_ideal)
    X_inst_conf_noisy.append(inst_p_noisy)




instance: 0


group: 0
1
0.7841096718117629


group: 1
1
0.9144100308540011


group: 2
0
0.04385662690792315


instance: 1


group: 0
1
0.6745824575706653


group: 1
1
0.7492289103259625


group: 2
1
0.7807601383792495


instance: 2


group: 0
1
0.8464743668573678


group: 1
1
0.7001572378276947


group: 2
0
0.029223964143491495


instance: 3


group: 0
1
0.8253238553915275


group: 1
0
0.7244671305644907


group: 2
0
0.7800495417400242


instance: 4


group: 0
1
0.9603025557871507


group: 1
1
0.8445907233721103


group: 2
0
0.13360980594617894


instance: 5


group: 0
0
0.10879073478839235


group: 1
1
0.7791973703136474


group: 2
0
0.27645443253043445


instance: 6


group: 0
1
0.4568272551752832


group: 1
1
0.9642090720701224


group: 2
1
0.9156048283815958


instance: 7


group: 0
0
0.35928614531161057


group: 1
0
0.07764604873098561


group: 2
1
0.9199129752583104


instance: 8


group: 0
0
0.10256647179865966


group: 1
1
0.9675570678479328


group: 2
1
0.7197406746151354



# Coordinates and Coordinate Confidence

In [3]:
for m in range(no_instances):
    
    
    print('\n')
    print(f'instance: {m}')
    

    #############################################################################
    ############## SET TRUE COORDINATE & IDEAL PROBABILITIES ####################
    #############################################################################


    # set all coordinate probabilities p = 0.0
    coordinate_p_ideal = np.zeros(no_puzzlepieces)

    # determine true coordinate and set its probability to p = 1.0
    i = random.randint(0,no_puzzlepieces-1)
    coordinate_p_ideal[i] = 1.0

    # show all probabilities
    print(coordinate_p_ideal)
    
    # store ideal probabilities
    X_coord_conf_ideal.append(coordinate_p_ideal)


    #############################################################################
    ########################  NORMALLY DISTRIBUTED NOISE ########################
    #############################################################################

    
    # auxilary lists to store different group's outputs per instance
    both_groups = []
    for group in range(2):

        # add normally distributed noise on ideal probabilities 
        coordinate_p_noisy = []
        for i in range(no_puzzlepieces):
            coordinate_p_noisy.append(np.random.normal(scale = std, loc = coordinate_p_ideal[i], size = 1)[0])

        # upscale values
        coordinate_p_noisy_upscaled = np.multiply(coordinate_p_noisy, scale_up_factor)                               

        # squash values to sum up to one to represent probabilities
        coordinate_p_noisy_squashed = softmax(coordinate_p_noisy_upscaled)

        # save group's probability distribution in overall df
        both_groups.append(coordinate_p_noisy_squashed)
        print(both_groups[group])

    #X.append(both_groups)
    X_coord_conf_noisy.append(both_groups)




instance: 0
[0. 0. 1.]
[0.04124953 0.01904038 0.93971009]
[0.46140804 0.30532401 0.23326794]


instance: 1
[1. 0. 0.]
[0.65795437 0.31250338 0.02954225]
[0.4818547 0.1586255 0.3595198]


instance: 2
[0. 0. 1.]
[0.17609948 0.4265488  0.39735171]
[0.39513847 0.13217835 0.47268318]


instance: 3
[0. 1. 0.]
[0.11852374 0.86615953 0.01531673]
[0.03816969 0.92652661 0.03530369]


instance: 4
[0. 1. 0.]
[0.06932046 0.90185197 0.02882758]
[0.15207313 0.81062367 0.0373032 ]


instance: 5
[0. 0. 1.]
[0.04212154 0.11060912 0.84726934]
[0.01456203 0.00364953 0.98178844]


instance: 6
[0. 0. 1.]
[0.05676338 0.0958668  0.84736982]
[0.00458838 0.00234389 0.99306773]


instance: 7
[0. 0. 1.]
[0.01317176 0.05772937 0.92909887]
[0.02135393 0.00899406 0.96965202]


instance: 8
[1. 0. 0.]
[0.82687401 0.06369186 0.10943413]
[0.81878948 0.14496099 0.03624953]


instance: 9
[0. 1. 0.]
[0.01457136 0.86614557 0.11928307]
[0.10199442 0.8194964  0.07850918]


# Moving Vector

In [21]:
#X_mov_vec = []
for m in range(no_instances):
    X_mov_vec.append(['dummy moving vector'])

# Gold Label

In [ ]:
for m in range(no_instances):
    
    # language group outputs  
    if df['Instruction'][m][2]==1:
        y.append(df['Moving Vector'][m])
        
    # language and vision group outputs
    elif df['Instruction'][m][0]==1:
        y.append(df['Coordinate'][m])
        
    # gesture group outputs
    elif df['Instruction'][m][1]==1:
        y.append(df['Coordinate'][m])
        
    # noone outputs
    else:
        y.append('NaN')
    
    print(f'instance: {m}')
    print(y[m])
    print('\n')


# Store All

In [22]:
X = {'Instruction':X_inst_conf_ideal,'Instruction Confidence':X_inst_conf_noisy, 'Coordinate': X_coord_conf_ideal , 'Coordinate Confidence':X_coord_conf_noisy, 'Moving Vector':X_mov_vec}
df_X = pd.DataFrame(X)
df_X


Instruction                             Instruction Confidence  \
0   [1, 1, 0]  [0.7841096718117629, 0.9144100308540011, 0.043...   
1   [1, 1, 1]  [0.6745824575706653, 0.7492289103259625, 0.780...   
2   [1, 1, 0]  [0.8464743668573678, 0.7001572378276947, 0.029...   
3   [1, 0, 0]  [0.8253238553915275, 0.7244671305644907, 0.780...   
4   [1, 1, 0]  [0.9603025557871507, 0.8445907233721103, 0.133...   
5   [0, 1, 0]  [0.10879073478839235, 0.7791973703136474, 0.27...   
6   [1, 1, 1]  [0.4568272551752832, 0.9642090720701224, 0.915...   
7   [0, 0, 1]  [0.35928614531161057, 0.07764604873098561, 0.9...   
8   [0, 1, 1]  [0.10256647179865966, 0.9675570678479328, 0.71...   
9   [1, 1, 0]  [0.6115830635929308, 0.9621033235042691, 0.952...   

        Coordinate                              Coordinate Confidence  \
0  [0.0, 0.0, 1.0]  [[0.041249526067349544, 0.019040380818150723, ...   
1  [1.0, 0.0, 0.0]  [[0.6579543734992308, 0.31250337982931914, 0.0...   
2  [0.0, 0.0, 1.0]  [[0.17609948228682942, 0.42654880287184166, 0....   
3  [0.0, 1.0, 0.0]  [[0.11852373809322488, 0.8661595336721475, 0.0...   
4  [0.0, 1.0, 0.0]  [[0.0693204576706093, 0.9018519659030165, 0.02...   
5  [0.0, 0.0, 1.0]  [[0.042121535313158646, 0.11060912141564094, 0...   
6  [0.0, 0.0, 1.0]  [[0.05676337909396009, 0.09586680168685952, 0....   
7  [0.0, 0.0, 1.0]  [[0.013171762798235684, 0.057729367936770096, ...   
8  [1.0, 0.0, 0.0]  [[0.8268740077131365, 0.06369186259792814, 0.1...   
9  [0.0, 1.0, 0.0]  [[0.014571358688395344, 0.8661455727437606, 0....   

           Moving Vector  
0  [dummy moving vector]  
1  [dummy moving vector]  
2  [dummy moving vector]  
3  [dummy moving vector]  
4  [dummy moving vector]  
5  [dummy moving vector]  
6  [dummy moving vector]  
7  [dummy moving vector]  
8  [dummy moving vector]  
9  [dummy moving vector]

In [40]:
y = {'DM output': y}
df_y = pd.DataFrame(data=y)
df_y

DM output
0        [0.0, 0.0, 1.0]
1  [dummy moving vector]
2        [0.0, 0.0, 1.0]
3        [0.0, 1.0, 0.0]
4        [0.0, 1.0, 0.0]
5        [0.0, 0.0, 1.0]
6  [dummy moving vector]
7  [dummy moving vector]
8  [dummy moving vector]
9        [0.0, 1.0, 0.0]